# Generated by Django 4.0.5 on 2022-10-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
